### PR TITLE
Refactor/js to ts

### PR DESCRIPTION
**Pull request by mimakuch**
Need help at this point. I'm not sure, if I typed correctly what I typed.
And need hint how to approach the rest.

### CODE REVIEW

**Review by Sumick — COMMENTED** [review]
Yea it looks good!

**Comment by Sumick** [comment]
In what part do you need hints specifically?

**Comment by mimakuch** [comment]
I managed to complete the task. All that's left is figure out why certain parts of app doesn't work properly :)

**Review by Sumick — CHANGES_REQUESTED** [review]
You should have `tsconfig.json` included in your repo (in this PR) - otherwise other dev working with you won't have properly working TS

**Review by Sumick — APPROVED** [review]
Good job on that battle! 🙌⚔️😎

**Pull request merged**
